### ISSUE TITLE
Frozen UI

### ISSUE THREAD

**Issue by sowdowdow** [BeamNG/remotecontrol#12]
Actually everything is working (steering wheel is turning well) except the UI.
It stay frozen to the same value :
![screenshot_2017-06-19-21-09-22](https://user-images.githubusercontent.com/26247667/27297047-5d36197c-5534-11e7-9909-388a4d45567b.png)

> LG G3 D855

> Android 6.0

**Comment by 50thomatoes50** [comment]
This is a know issue with some network the gauge can't get the values from the game

**Comment by sowdowdow** [comment]
![image](https://user-images.githubusercontent.com/26247667/27899963-6c516f4a-623d-11e7-98a2-5729ffda1629.png)
That was it.
