### ISSUE TITLE
HUD doesn't work sometimes

### ISSUE THREAD

**Issue by jhasse** [BeamNG/remotecontrol#2]
In some networks, the HUD (speed etc. on the phone), doesn't display anything. The steering does work though, so it's something related to UdpReceiver.

Some data from my home network, where it doesn't work:

```
PC IP: 192.168.1.113
Phone IP: 192.168.1.233
Broadcastaddress: 192.168.1.255
ReceiveSocketBinder: 192.168.1.233:4445
```

**Comment by Hondune** [comment]
Fixed with the new LUA and couple app changes
