### ISSUE TITLE
Bug with startup screen

### ISSUE THREAD

**Issue by tdev** [BeamNG/remotecontrol#9]
The start button disappears if you rotate the phone into landscape mode. You cannot even scroll, rendering the app useless in that mode.

**Comment by tdev** [comment]
was fixed already, my fault :)

**Comment by jhasse** [comment]
Unfortunately it's hard to notice that one can scroll down to see the button. I tried to fix this with a clever layout, but all the different screen sizes we need to support make this hard.

One solution would be to integrate the scan button into the action bar.
